"""Visual-spoof detection for user-controlled display strings.

Glyph metadata (token name, ticker, description) is supplied by the
deployer and rendered in caller UIs. A token deployer can put any
Unicode codepoints there — including Cyrillic, Greek, or Cherokee
letters that visually mimic Latin letters in most fonts. Without
detection, a deployer could create "USDC" with Cyrillic 'U' and 'С'
that looks identical to the legitimate USDC token in any caller's
UI.

This module provides two primitives backed by the Unicode TR39
"Security Mechanisms" data:

* :func:`skeleton` — reduce a string to its visual canonical form.
  Two strings that "look the same" produce identical skeletons.
* :func:`looks_confusable_with_latin` — high-level check that flags
  a string as a likely Latin-impersonating spoof.

The TR39 data file is vendored at ``src/pyrxd/glyph/_confusables.py``
and re-generated by ``scripts/vendor-confusables.py`` when Unicode
publishes a new security data release (annually).

Threat model and false-positive policy
--------------------------------------

The vendor script intentionally **drops ASCII source mappings**
(0x20–0x7E). TR39 includes correct assertions like "0 looks like O"
and "m looks like rn" — those are valid visual observations but
applying them in a token-name context produces bizarre false positives
(``"USDT1"`` → ``"USDTl"``, ``"mom"`` → ``"rnorn"``). Users write
ASCII digits and letters intentionally; spoof attacks come from
*non-ASCII* codepoints that resolve to ASCII-looking text. This
asymmetry is critical to the false-positive policy:

* Pure-Latin / Latin-Extended (``é``, ``ñ``, ``ü``) input: never
  flagged.
* ASCII digits and punctuation in legitimate names (``WBTC1``,
  ``TKN.123``): never flagged.
* Non-Latin script that *visually mimics* Latin: flagged.
* Non-Latin script with no Latin appearance (legitimate non-English
  token names like ``トークン``): not flagged here. Use the script-
  identification helpers in callers (e.g. the inspect tool's
  ``_suspicious_reason`` in ``glue.py``) for a softer "non-Latin
  script — verify by txid" advisory.
"""

from __future__ import annotations

import unicodedata

from ._confusables import skeleton

__all__ = ["looks_confusable_with_latin", "skeleton"]


# Bidi formatting controls. These reorder rendered text without changing
# byte sequence, so an attacker can register "CDSU" with U+202E prepended
# and have UIs render it as "USDC". We reject any string containing one
# of these as a Latin-impersonation spoof regardless of the skeleton
# reduction. Range covers RLE/LRE/PDF/RLO/LRO (U+202A–202E) and the
# isolate set (U+2066–2069).
_BIDI_FORMAT_CONTROLS = frozenset(range(0x202A, 0x202F)) | frozenset(range(0x2066, 0x206A))


def looks_confusable_with_latin(s: str) -> bool:
    """Return True if *s* visually impersonates Latin text.

    Detection covers four attack shapes:

    1. **Confusable substitution.** A non-Latin Letter (Cyrillic,
       Greek, Cherokee, etc.) whose TR39 skeleton is a Latin Letter.
       Examples: ``"USDС"`` (final char Cyrillic С), ``"ВТС"`` (pure
       Cyrillic mimicking BTC), ``"ΟΜΓ"`` (Greek mimicking OMG).
    2. **NFKC compatibility folds.** Compatibility codepoints that
       fold to ASCII Latin. Mathematical Alphanumeric Symbols
       (``"𝐔𝐒𝐃𝐂"``) and other styled-Latin blocks are visually
       distinct from plain ASCII but renderable as a near-perfect
       spoof.
    3. **Specialty / phonetic Latin homoglyphs.** Codepoints in U+0250+
       (IPA Extensions, Phonetic Extensions, Latin Extended
       Additional, small-caps blocks) that have ``"LATIN"`` in their
       Unicode name but visually resemble common Latin letters.
       Examples: ``"ɑpple"`` (IPA alpha U+0251 → a), ``"ɓ"`` (Latin
       small B with hook U+0253 → b̔). Distinct from common Latin
       Extended (Polish Ł, ligature Œ, German ß, Polish/Czech
       diacritics) which live in U+00C0–U+024F and are NOT flagged.
    4. **Bidi reordering.** Strings containing RLO/LRO/RLE/LRE/PDF or
       the isolate-control set. These reorder pure-ASCII bytes
       visually, so ``"\\u202eCDSU"`` renders as "USDC" without
       containing a non-ASCII letter. Flagged unconditionally.

    Examples flagged:

    * ``"USDС"`` (Cyrillic С) — substitution.
    * ``"𝐔𝐒𝐃𝐂"`` (Mathematical Bold) — NFKC fold.
    * ``"ɑpple"`` (IPA alpha) — specialty Latin homoglyph.
    * ``"\\u202eCDSU"`` — bidi reorder.
    * ``"USDСö"`` (Cyrillic С + Arabic ö appendage) — the per-char
      check sees the Cyrillic spoof regardless of trailing
      non-Latin Letters.

    Examples NOT flagged:

    * ``"USDC"`` — pure ASCII Latin.
    * ``"Café"``, ``"naïve"``, ``"Łódź"``, ``"Œuf"`` — common Latin
      Extended (U+00C0–U+024F).
    * ``"トークン"``, ``"中文"`` — non-Latin scripts that aren't
      impersonating Latin.
    * ``"USDT1"``, ``"WBTC2"`` — digits are ASCII; the vendor
      script intentionally drops ASCII-source confusables to
      prevent false positives on legitimate digit-suffixed names.

    Mixed-script branding (token names like ``"USD-Доллар"`` that
    deliberately mix Latin and Cyrillic) IS flagged. The SDK can't
    distinguish "intentional Russian brand" from "Latin spoof"; the
    caller surfaces this as a warning, not a hard reject.

    The function is total: any non-string input returns False.
    """
    if not isinstance(s, str) or not s:
        return False

    # Attack shape 4: bidi control reordering. A pure-ASCII spoof
    # made by reversing rendered text is invisible to the skeleton
    # reduction (no non-Latin letter to substitute). Catch it
    # explicitly before any other check.
    if any(ord(ch) in _BIDI_FORMAT_CONTROLS for ch in s):
        return True

    # Walk the *original* string char by char and check each one for
    # spoof shapes. Doing it per-character (rather than comparing
    # whole-string normalised forms) prevents the appendage-bypass
    # attack: an attacker can't append one non-Latin Letter
    # to a Math-Bold spoof and get back below the radar.
    #
    # Per-char detection covers three spoof shapes plus the bidi
    # check above:
    #
    #   - NFKC compatibility fold: char NFKC-folds from non-ASCII to
    #     ASCII Latin (Math Bold 𝐔→U; fullwidth Ｕ→U; circled Ⓤ→U;
    #     Roman numeral Ⅸ→IX; ligature ﬁ→fi).
    #   - TR39 confusable substitution: char's skeleton is Latin
    #     (Cyrillic С→C; Greek Ο→O; Cherokee letters; IPA ɑ→a).
    #   - Mixed source/target: the per-char approach handles the
    #     "USDСö" appendage-bypass automatically because each char
    #     is checked on its own merits.
    #
    # Three classes of false positive that this approach side-steps:
    #
    #   - Decomposition of common Latin Extended (Polish Ł reduces
    #     under TR39 to "L̸"; ligature Œ to "OE"; German ß to "ss").
    #     Both source and target are Latin — not impersonation. The
    #     U+0250 cutoff distinguishes common-language Latin (legit)
    #     from specialty/phonetic Latin (homoglyphs).
    #   - Pure-ASCII Latin: every char skeleton == char and NFKC-
    #     normalisation is a no-op. The loop short-circuits.
    #   - Pure-non-Latin scripts (Japanese トークン, Chinese 中文):
    #     no char NFKC-folds to Latin and no char's TR39 skeleton
    #     is Latin, so nothing flags.
    #
    # Mixed-script branding ("USD-Доллар") IS flagged. The SDK can't
    # distinguish "intentional Russian brand" from "Latin spoof"; the
    # caller surfaces this as a warning, not a hard reject.
    for ch in s:
        # Per-char NFKC fold check. If this character alone NFKC-
        # decomposes to a string that is all-Latin-or-neutral AND
        # different from the source, the source is a styled-Latin
        # codepoint (Math Alphanumerics, fullwidth, circled, Roman
        # numerals, ligatures). Catches Math Bold 𝐔, fullwidth Ｕ,
        # circled Ⓤ, etc. — and survives any subsequent appendage
        # of unrelated non-Latin chars because we look at each
        # character independently.
        if ord(ch) > 0x7F:
            ch_nfkc = unicodedata.normalize("NFKC", ch)
            # ch folds to all-Latin AND at least one codepoint in the
            # fold is a Latin Letter — so a fold like ﹙ → ( doesn't
            # false-positive on punctuation-only NFKC reductions.
            if (
                ch_nfkc != ch
                and ch_nfkc
                and all(_is_latin_or_neutral(c) for c in ch_nfkc)
                and any(unicodedata.category(c).startswith("L") for c in ch_nfkc)
            ):
                return True

        if not unicodedata.category(ch).startswith("L"):
            # Non-Letter (digit, punctuation, combining mark, symbol).
            # Even if it has a TR39 mapping, it's not a Latin-letter
            # spoof. Skip.
            continue
        ch_skel = skeleton(ch)
        if ch_skel == ch:
            # No reduction. ASCII Latin (A-Z), Latin Extended that
            # doesn't impersonate anything (Café's é, Müller's ü,
            # Žižek's ž), or any other letter TR39 considers visually
            # canonical. Not a confusable source.
            continue
        # The skeleton differs. ch is a TR39 confusable source. Three
        # remaining cases to distinguish:
        #
        #   (a) Non-Latin Letter that reduces to Latin (Cyrillic С → C,
        #       Greek Ο → O, Cherokee letters). Always a spoof.
        #   (b) Specialty / phonetic Latin Letter that reduces to
        #       common Latin (IPA ɑ U+0251 → a; Latin small B with hook
        #       ɓ U+0253 → b̔ (b + mark); Latin small capitals U+1D00+).
        #       These have "LATIN" in their Unicode name but visually
        #       impersonate common Latin letters in normal display
        #       fonts. Treat as spoofs.
        #   (c) Common-language Latin Extended (Polish Ł → L̸; ligature
        #       Œ → OE; ß → ss). Decomposition for a real language.
        #       Not a spoof.
        #
        # Range cut: codepoints U+0000–U+024F are Basic Latin + Latin-1
        # Supplement + Latin Extended-A + Latin Extended-B (the common
        # everyday-language ranges, where Ł, Œ, Š, ß live). Codepoints
        # U+0250+ enter IPA Extensions, Phonetic Extensions, Latin
        # Extended Additional, and the various small-capital / styled
        # blocks where homoglyph attacks live.
        if _is_latin_letter(ch) and ord(ch) < 0x0250:
            # Common-language Latin source. Reduction is decomposition,
            # not impersonation.
            continue
        # ch is either non-Latin Letter (case a) or specialty-Latin
        # Letter ≥ U+0250 (case b). Either way, if its skeleton reads
        # as Latin, the source impersonates Latin.
        skel_letters = [c for c in ch_skel if unicodedata.category(c).startswith("L")]
        if not skel_letters:
            # Skeleton has no Letters (e.g. punctuation-only target).
            # Not a Latin-impersonation.
            continue
        if all(_is_latin_letter(c) and ord(c) < 0x0250 for c in skel_letters):
            return True

    # No individual confusable mapped to common Latin. Not a spoof.
    return False


def _is_latin_letter(ch: str) -> bool:
    """A Letter codepoint whose Unicode name starts with 'LATIN '. Used
    by the Latin-letter sequence comparison so non-Latin Letter blocks
    (Cyrillic, Greek, Arabic, etc.) drop out of the comparison."""
    cat = unicodedata.category(ch)
    if not cat.startswith("L"):
        return False
    try:
        name = unicodedata.name(ch)
    except ValueError:
        return False
    return name.startswith("LATIN ")


def _is_latin_or_neutral(ch: str) -> bool:
    """A char that's either a Latin Letter or a non-Letter (digit,
    punctuation, symbol). Used by ``looks_confusable_with_latin`` to
    answer "does this read as Latin?". A skeleton consisting of Latin
    letters and ASCII digits is "looks like Latin"; one with any
    non-Latin Letter is not.

    Codepoints with no Unicode name (PUA, surrogates, unassigned)
    return False — we conservatively treat them as non-Latin so a
    skeleton containing one fails the "all-Latin" check."""
    cat = unicodedata.category(ch)
    if not cat.startswith("L"):
        return True
    try:
        name = unicodedata.name(ch)
    except ValueError:
        return False
    return name.startswith("LATIN ")
