"""Visual-spoof detection for user-controlled display strings.

Glyph metadata (token name, ticker, description) is supplied by the
deployer and rendered in caller UIs. A token deployer can put any
Unicode codepoints there — including Cyrillic, Greek, or Cherokee
letters that visually mimic Latin letters in most fonts. Without
detection, a deployer could create "USDC" with Cyrillic 'U' and 'С'
that looks identical to the legitimate USDC token in any caller's
UI.

This module provides two primitives backed by the Unicode TR39
"Security Mechanisms" data:

* :func:`skeleton` — reduce a string to its visual canonical form.
  Two strings that "look the same" produce identical skeletons.
* :func:`looks_confusable_with_latin` — high-level check that flags
  a string as a likely Latin-impersonating spoof.

The TR39 data file is vendored at ``src/pyrxd/glyph/_confusables.py``
and re-generated by ``scripts/vendor-confusables.py`` when Unicode
publishes a new security data release (annually).

Threat model and false-positive policy
--------------------------------------

The vendor script intentionally **drops ASCII source mappings**
(0x20–0x7E). TR39 includes correct assertions like "0 looks like O"
and "m looks like rn" — those are valid visual observations but
applying them in a token-name context produces bizarre false positives
(``"USDT1"`` → ``"USDTl"``, ``"mom"`` → ``"rnorn"``). Users write
ASCII digits and letters intentionally; spoof attacks come from
*non-ASCII* codepoints that resolve to ASCII-looking text. This
asymmetry is critical to the false-positive policy:

* Pure-Latin / Latin-Extended (``é``, ``ñ``, ``ü``) input: never
  flagged.
* ASCII digits and punctuation in legitimate names (``WBTC1``,
  ``TKN.123``): never flagged.
* Non-Latin script that *visually mimics* Latin: flagged.
* Non-Latin script with no Latin appearance (legitimate non-English
  token names like ``トークン``): not flagged here. Use the script-
  identification helpers in callers (e.g. the inspect tool's
  ``_suspicious_reason`` in ``glue.py``) for a softer "non-Latin
  script — verify by txid" advisory.
"""

from __future__ import annotations

import unicodedata

from ._confusables import skeleton

__all__ = ["looks_confusable_with_latin", "skeleton"]


def looks_confusable_with_latin(s: str) -> bool:
    """Return True if *s* contains non-ASCII characters that visually
    mimic Latin letters.

    Detection rule:

    1. NFKC-normalise *s* so compatibility forms (full-width letters,
       fraction-slash) collapse to canonical form.
    2. Apply the TR39 skeleton reduction.
    3. If the original contained any non-Latin Letter codepoints, but
       the skeleton is **entirely** Latin / ASCII, the original was a
       Latin-impersonating spoof.

    Examples:

    * ``"USDC"`` → ``False`` (pure Latin, skeleton equals input).
    * ``"USDС"`` (final char Cyrillic) → ``True`` (skeleton is Latin
      "USDC" but the original is mixed).
    * ``"ВТС"`` (all Cyrillic; mimics "BTC") → ``True`` (skeleton is
      Latin "BTC" but the original is non-Latin).
    * ``"トークン"`` → ``False`` (skeleton is non-Latin Japanese; not
      a Latin-impersonating attack).
    * ``"Café"`` → ``False`` (Latin Extended; skeleton stays Latin
      Extended, no spoof shape).
    * ``"USDT1"`` → ``False`` (digit 1 is ASCII; not a confusable
      source per our vendor filter).

    The function is total: any non-string input returns False.
    """
    if not isinstance(s, str) or not s:
        return False
    normalised = unicodedata.normalize("NFKC", s)
    skel = skeleton(normalised)

    # If the skeleton equals the (NFKC-normalised) original, no
    # confusable substitution happened — definitely not a spoof.
    if skel == normalised:
        return False

    # The skeleton differs. The relevant question now is: did the
    # reduction produce a Latin / ASCII string from a non-Latin
    # original? If so, it's a Latin-impersonation spoof.
    has_non_latin_letter = any(_is_non_latin_letter(ch) for ch in normalised)
    if not has_non_latin_letter:
        # Original was entirely Latin Letters (or non-Letters); the
        # skeleton change must have come from a non-Letter codepoint
        # (e.g. punctuation reduction). Not a spoof shape.
        return False

    skeleton_is_latin = all(_is_latin_or_neutral(ch) for ch in skel)
    return skeleton_is_latin


def _is_non_latin_letter(ch: str) -> bool:
    """A Letter codepoint whose Unicode name does not start with "LATIN ".
    Excludes Latin Extended (legitimate non-English Latin) — those are
    Letters with names like "LATIN SMALL LETTER E WITH ACUTE"."""
    cat = unicodedata.category(ch)
    if not cat.startswith("L"):
        return False
    try:
        name = unicodedata.name(ch)
    except ValueError:
        # No assigned name (PUA, surrogate, unassigned). Treat as
        # non-Latin to err on the side of flagging.
        return True
    return not name.startswith("LATIN ")


def _is_latin_or_neutral(ch: str) -> bool:
    """A char that's either a Latin Letter or a non-Letter (digit,
    punctuation, symbol). Used by ``looks_confusable_with_latin`` to
    answer "is this skeleton entirely Latin-or-non-letter?". A
    skeleton consisting of Latin letters and ASCII digits is "looks
    like Latin"; one with any non-Latin Letter is not."""
    cat = unicodedata.category(ch)
    if not cat.startswith("L"):
        return True
    try:
        name = unicodedata.name(ch)
    except ValueError:
        return False
    return name.startswith("LATIN ")
