"""Tests for ``pyrxd.glyph.confusables`` — TR39 visual-spoof detection.

The vendored TR39 confusables table is generated by
``scripts/vendor-confusables.py`` and lives at
``src/pyrxd/glyph/_confusables.py``. These tests pin the
behaviour we promise to callers:

  - Realistic spoof attacks against ASCII Latin token names are
    detected (Cyrillic / Greek / IPA letters that visually mimic
    Latin).
  - Legitimate input is never flagged. False positives matter:
    if "Café" or "USDT1" trips the spoof detector, we damage
    legitimate non-English-Latin and digit-suffixed token names
    more than the attack we're defending against.
  - Pure-non-Latin scripts that are NOT trying to look Latin
    (Japanese, Chinese, Korean) are not flagged here. The inspect
    tool's ``_suspicious_reason`` applies a softer "non-Latin —
    verify by txid" advisory for those.

If the vendored table is regenerated, these tests must continue to
pass — they encode the intent of the data, not its exact contents.
"""

from __future__ import annotations

import pytest

from pyrxd.glyph.confusables import looks_confusable_with_latin, skeleton


class TestSkeleton:
    """``skeleton`` applies the TR39 confusable reduction to every
    character of the input."""

    def test_pure_ascii_round_trips(self):
        for s in ["USDC", "BTC", "TKN.123", "WBTC2", "Hello world!"]:
            assert skeleton(s) == s, f"ASCII input changed: {s!r} -> {skeleton(s)!r}"

    def test_latin_extended_round_trips(self):
        # Accented Latin letters are themselves "LATIN ..." per
        # unicodedata.name and shouldn't reduce to plain ASCII.
        # Café staying "Café" matters more than reducing to "Cafe".
        for s in ["Café", "naïve", "piñata", "Zürich", "résumé"]:
            assert skeleton(s) == s, f"Latin Extended changed: {s!r} -> {skeleton(s)!r}"

    def test_cyrillic_letters_reduce_to_latin(self):
        # The classic homoglyph test: skeleton of a Cyrillic-spoofed
        # name equals the Latin string it impersonates.
        assert skeleton("ВТС") == "BTC"  # Cyrillic В Т С → Latin
        assert skeleton("аррӏе") == "apple"
        assert skeleton("USDС") == "USDC"  # final char Cyrillic С

    def test_greek_letters_reduce_to_latin(self):
        # Greek capital omicron / mu / etc. visually overlap Latin O / M.
        # Note: not every Greek letter has a Latin confusable. Capital
        # Gamma (Γ) doesn't reduce to G — it's visually open at the
        # bottom where G is closed, so TR39 doesn't claim they're
        # confusable. Test only the pairs that genuinely are.
        assert skeleton("Ο") == "O"  # Greek capital omicron → Latin O
        assert skeleton("Μ") == "M"  # Greek capital mu → Latin M
        assert skeleton("Ι") == "l"  # Greek capital iota → Latin l (TR39 reduces I-likes to l)
        assert skeleton("Α") == "A"  # Greek capital alpha → Latin A

    def test_ascii_digits_NOT_in_table(self):
        # The vendor script intentionally drops ASCII source mappings
        # to prevent false positives. Verify "1" / "0" / "5" pass
        # through unchanged.
        for digit in "0123456789":
            assert skeleton(digit) == digit

    def test_ascii_lowercase_letters_NOT_in_table(self):
        # Same false-positive guard: lowercase Latin letters as sources
        # would map to multi-char targets ("m" → "rn"), corrupting
        # legitimate English input.
        for letter in "abcdefghijklmnopqrstuvwxyz":
            assert skeleton(letter) == letter, f"Lowercase {letter!r} reduced"

    def test_empty_string(self):
        assert skeleton("") == ""

    def test_non_string_passthrough(self):
        # The function is total: anything not a string returns as-is.
        # This is documented in the public docstring.
        assert skeleton(None) is None
        assert skeleton(42) == 42


class TestLooksConfusableWithLatin:
    """``looks_confusable_with_latin`` flags Latin-impersonating
    spoofs while passing through legitimate input."""

    @pytest.mark.parametrize(
        "spoof",
        [
            "USDС",  # Cyrillic С
            "USDС",  # Cyrillic capital ES, same as above
            "ВТС",  # all-Cyrillic mimicking BTC
            "аррӏе",  # all-Cyrillic mimicking "apple" (with IPA letter)
            "ВNВ",  # Cyrillic V's around Latin N
            "BNB" + "С",  # mixed: Latin BNB + Cyrillic С as final
        ],
    )
    def test_spoof_attacks_flagged(self, spoof):
        assert looks_confusable_with_latin(spoof), f"missed spoof: {spoof!r}"

    @pytest.mark.parametrize(
        "legit",
        [
            "USDC",
            "BNB",
            "BTC",
            "USDT",
            "Token",
            "MyToken-2",
            "WBTC2",
            "USDT1",
            "TKN.123",
            "A.B.C-1",
            "Hello world",
            "12345",
            "🚀TOKEN",
            "🚀",
        ],
    )
    def test_legitimate_ascii_not_flagged(self, legit):
        assert not looks_confusable_with_latin(legit), f"false positive: {legit!r}"

    @pytest.mark.parametrize(
        "latin_extended",
        [
            "Café",
            "naïve",
            "piñata",
            "Zürich",
            "résumé",
            "Tarzán",
            "Müller",
        ],
    )
    def test_latin_extended_not_flagged(self, latin_extended):
        """Real-world non-English Latin token names use accented
        characters routinely. False-positiving these would damage
        trust in the legitimate non-English token namespace."""
        assert not looks_confusable_with_latin(latin_extended), f"false positive: {latin_extended!r}"

    @pytest.mark.parametrize(
        "non_latin",
        [
            "トークン",  # Japanese katakana
            "中文",  # Chinese
            "한국어",  # Korean
            "ハナ",  # Japanese, with combining mark
        ],
    )
    def test_pure_non_latin_scripts_not_flagged(self, non_latin):
        """Non-Latin token names that are NOT trying to look Latin are
        not flagged here. The inspect tool's ``_suspicious_reason``
        applies a softer 'non-Latin script — verify by txid' advisory
        instead."""
        assert not looks_confusable_with_latin(non_latin), f"false positive on legitimate non-Latin: {non_latin!r}"

    @pytest.mark.parametrize("bad", [None, 42, [], {}, b"bytes"])
    def test_non_string_input_returns_false(self, bad):
        assert looks_confusable_with_latin(bad) is False

    def test_empty_string_returns_false(self):
        assert looks_confusable_with_latin("") is False

    def test_fullwidth_latin_flagged_as_compat_fold(self):
        """Pure fullwidth Latin (ＵＳＤＣ) NFKC-folds to ASCII USDC.
        Round-1 audit (PR #57) initially treated this as benign on
        the reasoning that it's "still Latin"; round-2 audit (F-1)
        correctly flagged it as a styled-Latin spoof shape — visually
        identical to USDC in most fonts, byte-different. Now caught
        by the NFKC-compat-fold check."""
        full_width_latin = "ＵＳＤＣ"
        assert looks_confusable_with_latin(full_width_latin)


class TestFacadeReExport:
    """``pyrxd.glyph.inspect`` re-exports ``skeleton`` and
    ``looks_confusable_with_latin`` as part of its stable public API."""

    def test_skeleton_re_exported(self):
        from pyrxd.glyph.inspect import skeleton as facade_skeleton

        assert facade_skeleton("USDС") == "USDC"

    def test_looks_confusable_re_exported(self):
        from pyrxd.glyph.inspect import looks_confusable_with_latin as facade_check

        assert facade_check("USDС") is True
        assert facade_check("USDC") is False

    def test_in_facade_all(self):
        from pyrxd.glyph import inspect

        assert "skeleton" in inspect.__all__
        assert "looks_confusable_with_latin" in inspect.__all__


class TestVendorScriptOutput:
    """Sanity checks against the vendored ``_confusables.py`` module
    so a future re-vendor doesn't silently regress the false-positive
    policy."""

    def test_no_ascii_source_codepoints_in_table(self):
        """The vendor script drops ASCII source mappings (0x20-0x7E)
        to prevent false positives like 'm' -> 'rn'. Verify the
        invariant holds."""
        from pyrxd.glyph._confusables import _CONFUSABLE_MAP

        for cp in _CONFUSABLE_MAP:
            assert not (0x20 <= cp < 0x7F), f"ASCII source codepoint U+{cp:04X} leaked into vendored table"

    def test_table_contains_known_attack_codepoints(self):
        """Lock in the most-exploited Cyrillic spoof codepoints. If a
        future re-vendor accidentally drops these, we'd silently lose
        protection against the highest-impact attacks."""
        from pyrxd.glyph._confusables import _CONFUSABLE_MAP

        # Cyrillic uppercase letters that look like Latin.
        # U+0410 А → A; U+0412 В → B; U+0421 С → C; U+0415 Е → E;
        # U+041D Н → H; U+041A К → K; U+041C М → M; U+041E О → O;
        # U+0420 Р → P; U+0422 Т → T; U+0425 Х → X.
        for cp in [0x0410, 0x0412, 0x0421, 0x0415, 0x041D, 0x041A, 0x041C, 0x041E, 0x0420, 0x0422, 0x0425]:
            assert cp in _CONFUSABLE_MAP, f"missing critical Cyrillic→Latin mapping U+{cp:04X}"

    def test_no_control_or_format_chars_in_targets(self):
        """No mapping target may contain a Cc (control) or Cf (format)
        codepoint. A skeleton containing an invisible separator or
        bidi control would silently inject formatting bytes into the
        caller's display when the caller renders the skeleton.
        Discovered during round-1 audit; vendor Filter 3 enforces it."""
        import unicodedata

        from pyrxd.glyph._confusables import _CONFUSABLE_MAP

        offenders = []
        for cp, target in _CONFUSABLE_MAP.items():
            for ch in target:
                if unicodedata.category(ch) in ("Cc", "Cf"):
                    offenders.append((cp, target))
                    break
        assert offenders == [], f"Cc/Cf in target: {offenders[:5]}"

    def test_supplementary_plane_codepoints_emit_correctly(self):
        """The vendor script's emit step must use ``\\UXXXXXXXX``
        (8 hex) for codepoints above U+FFFF. The 4-hex form silently
        truncates supplementary-plane codepoints and produces a
        subtly wrong literal. The audit's flagged 'U+2F80D → \\u2063a'
        was actually U+2F80D → U+2063A (a single CJK char) corrupted
        by 4-hex emit. Lock in the fix."""
        from pyrxd.glyph._confusables import _CONFUSABLE_MAP

        # U+2F80D (CJK Compat Ideograph) maps to U+2063A — single
        # supplementary CJK char. Verify it round-trips.
        target = _CONFUSABLE_MAP.get(0x2F80D)
        if target is not None:
            assert len(target) == 1, f"U+2F80D target corrupted: {target!r}"
            assert ord(target) == 0x2063A


class TestAttackBypassesAddressedInRound1Audit:
    """Round-1 audit on PR #57 found three real bypasses against the
    initial detection logic. These tests pin the fixes:

      F-1: Mathematical Alphanumeric Symbols (NFKC-fold to ASCII Latin)
      F-2: RLO/LRO bidi reordering of pure ASCII
      F-3: IPA / specialty Latin homoglyphs (LATIN-named non-ASCII chars)
      F-appendage: appending non-Latin Letter to break naive whole-string check
    """

    def test_F1_mathematical_bold_flagged(self):
        # 𝐔𝐒𝐃𝐂 = U+1D414 U+1D412 U+1D403 U+1D402 (Math Bold). NFKC-folds
        # to ASCII "USDC". Visually: a near-perfect spoof of USDC.
        assert looks_confusable_with_latin("𝐔𝐒𝐃𝐂")

    def test_F1_mathematical_sans_serif_flagged(self):
        assert looks_confusable_with_latin("𝗨𝗦𝗗𝗖")

    def test_F1_mathematical_monospace_flagged(self):
        # U+1D670+ Mathematical Monospace.
        assert looks_confusable_with_latin("𝚄𝚂𝙳𝙲")

    def test_F1_fullwidth_flagged(self):
        # Pure fullwidth Latin is the same shape as Mathematical Bold:
        # a styled-Latin block whose codepoints NFKC-fold to ASCII.
        # Round-1 missed this; round-2 catches it via the NFKC fold.
        assert looks_confusable_with_latin("ＵＳＤＣ")

    def test_F2_RLO_prefix_flagged(self):
        # U+202E RIGHT-TO-LEFT OVERRIDE prefix reorders rendered text.
        # "‮CDSU" renders as USDC.
        assert looks_confusable_with_latin("‮CDSU")

    def test_F2_LRO_prefix_flagged(self):
        assert looks_confusable_with_latin("‭ABCD")

    def test_F2_RLE_flagged(self):
        assert looks_confusable_with_latin("‫ABCD")

    def test_F2_isolate_controls_flagged(self):
        # The isolate-control set: U+2066 LRI, U+2067 RLI, U+2068 FSI,
        # U+2069 PDI. Less commonly used but still reorder text.
        for cp in (0x2066, 0x2067, 0x2068, 0x2069):
            assert looks_confusable_with_latin(chr(cp) + "ABCD"), f"missed U+{cp:04X}"

    def test_F3_IPA_alpha_flagged(self):
        # ɑ (U+0251 LATIN SMALL LETTER ALPHA) → a per TR39. Is
        # "LATIN"-named per Unicode, but visually impersonates Cyrillic
        # а / Latin a in normal display fonts. The U+0250+ heuristic
        # treats specialty-Latin blocks as homoglyphs, not legitimate
        # language.
        assert looks_confusable_with_latin("ɑpple")

    def test_F3_IPA_b_with_hook_flagged(self):
        # ɓ (U+0253) → b̔ per TR39. Same shape as F3.
        assert looks_confusable_with_latin("ABCDɓ")

    def test_appendage_bypass_does_not_disable_detection(self):
        """Audit F1 finding: appending a non-Latin Letter (Arabic ö,
        Greek λ) to a Cyrillic-spoofed name shouldn't disable the
        spoof detection. Pin the fix."""
        assert looks_confusable_with_latin("USDСö")
        assert looks_confusable_with_latin("USDСλ")
        assert looks_confusable_with_latin("ВТСö")
        assert looks_confusable_with_latin("USDСöبكلام")
