"""dMint V2 covenant byte-match against the canonical Photonic redesign.

The FIXED vectors were generated by running the canonical
``Radiant-Core/Photonic-Wallet`` ``dMintScript`` (``packages/lib/src/script.ts``,
post-2026-05-26 redesign) directly under ``bun`` for representative parameter
sets, then captured verbatim. pyrxd's ``build_dmint_contract_script`` MUST
reproduce them byte-for-byte — that equality is the whole point of the redesign
(pyrxd had drifted from upstream's covenant; #219).

The ASERT and LWMA vectors were REGENERATED on 2026-09-16. Photonic replaced the
ASERT retarget with the fractional ASERT-v2 on 2026-06-19 (``ed53cd41``) and LWMA
with the damped LWMA-v2 on 2026-06-20 (``c90e6506``); the bun-generated vectors
captured here on 2026-06-16 pinned the retired formulas, so pyrxd's builders had
been "byte-matched" to bytecode upstream no longer emits. The four DAA vectors
below were rebuilt by splicing the DAA fragment produced by an INDEPENDENT
transcription of ``buildAsertDaaBytecode`` / ``buildLinearDaaBytecode`` at Photonic
commit ``becf41a731e78ab98fdd88652527d7dda12784c6`` (the hex arrays in
``tests/test_dmint_daa_v2_resync.py``) into the previously bun-generated vectors —
only the DAA fragment changed; state, Part A, Part B1/B2/B4 and Part C are the
2026-06-16 bun output verbatim. They were NOT produced by re-running ``bun``. The
pre-resync ASERT/LWMA vectors survive, unchanged, as the frozen-legacy goldens in
``tests/test_dmint_daa_v2_resync.py`` (contracts deployed under them keep mining).

If a vector here fails, pyrxd's V2 covenant has diverged from canonical Photonic.
Regenerate the vectors from the upstream source before "fixing" the test.

Contract refs in every vector: contractRef = aa*36, tokenRef = bb*36.
SHA256d only (the covenant compares 64-bit targets; difficulty d → target
MAX_SHA256D_TARGET // d). blake3/k12 differ only in the powHashOp + algoId byte.
"""

from __future__ import annotations

import warnings

import pytest

from pyrxd.glyph.dmint import (
    DaaMode,
    DmintAlgo,
    DmintDeployParams,
    build_dmint_contract_script,
)
from pyrxd.glyph.types import GlyphRef

_CONTRACT_REF = GlyphRef.from_bytes(bytes.fromhex("aa" * 36))
_TOKEN_REF = GlyphRef.from_bytes(bytes.fromhex("bb" * 36))

# label -> (DmintDeployParams kwargs, canonical contract-script hex)
_GOLDEN: dict[str, tuple[dict, str]] = {
    "fixed_h0": (
        dict(height=0, max_height=100, reward=1000, difficulty=10, target_time=60),
        "00d8aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        "d0bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb01"
        "6402e8030000013c040000000008cccccccccccccc0cbdc0c859797ea85d795d797ea87e5e7a"
        "7eaabc01147f77587f040000000088817600a26951797ca2696b75757575577ae500a069567a"
        "e600a06901d053797e0cdec0e9aa76e378e4a269e69d7eaa76e47b9d547a818b76537a9c537a"
        "de789181547ae6939d636c755279cd01d853797e016a7e886778de519d7676009c6375010067"
        "7660a163015093518067827c7e68684c53d8aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaad0bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
        "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbb016402e8030000013c7ec55480547c7e7e6c76009c6375"
        "0100677660a163015093518067827c7e68687e5379ec78885379eac0e9885379cc519d75686d"
        "7551",
    ),
    "fixed_h1": (
        dict(height=1, max_height=100, reward=1000, difficulty=10, target_time=60),
        "51d8aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        "d0bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb01"
        "6402e8030000013c040000000008cccccccccccccc0cbdc0c859797ea85d795d797ea87e5e7a"
        "7eaabc01147f77587f040000000088817600a26951797ca2696b75757575577ae500a069567a"
        "e600a06901d053797e0cdec0e9aa76e378e4a269e69d7eaa76e47b9d547a818b76537a9c537a"
        "de789181547ae6939d636c755279cd01d853797e016a7e886778de519d7676009c6375010067"
        "7660a163015093518067827c7e68684c53d8aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaad0bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
        "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbb016402e8030000013c7ec55480547c7e7e6c76009c6375"
        "0100677660a163015093518067827c7e68687e5379ec78885379eac0e9885379cc519d75686d"
        "7551",
    ),
    "fixed_h42": (
        dict(height=42, max_height=1000000, reward=50000, difficulty=10, target_time=60),
        "012ad8aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        "aad0bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
        "0340420f0350c3000000013c040000000008cccccccccccccc0cbdc0c859797ea85d795d797e"
        "a87e5e7a7eaabc01147f77587f040000000088817600a26951797ca2696b75757575577ae500"
        "a069567ae600a06901d053797e0cdec0e9aa76e378e4a269e69d7eaa76e47b9d547a818b7653"
        "7a9c537ade789181547ae6939d636c755279cd01d853797e016a7e886778de519d7676009c63"
        "750100677660a163015093518067827c7e68684c56d8aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaad0bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
        "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb0340420f0350c3000000013c7ec55480547c7e"
        "7e6c76009c63750100677660a163015093518067827c7e68687e5379ec78885379eac0e98853"
        "79cc519d75686d7551",
    ),
    "asert_h0": (
        dict(
            height=0, max_height=100, reward=1000, difficulty=10, daa_mode=DaaMode.ASERT, target_time=60, half_life=3600
        ),
        "00d8aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        "d0bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb01"
        "6402e8030052013c040000000008cccccccccccccc0cbdc0c859797ea85d795d797ea87e5e7a"
        "7eaabc01147f77587f040000000088817600a26951797ca269c5527994537994030000019502"
        "100e96020040a30200c0a47c08ffffffffffffff1fa37603000001967b959308ffffffffffff"
        "ff1fa376519f637551686b75757575577ae500a069567ae600a06901d053797e0cdec0e9aa76"
        "e378e4a269e69d7eaa76e47b9d547a818b76537a9c537ade789181547ae6939d636c755279cd"
        "01d853797e016a7e886778de519d7676009c63750100677660a163015093518067827c7e6868"
        "4c53d8aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        "aad0bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
        "016402e8030052013c7ec55480547c7e7e6c76009c63750100677660a163015093518067827c"
        "7e68687e5379ec78885379eac0e9885379cc519d75686d7551",
    ),
    "asert_hl600": (
        dict(
            height=5, max_height=100, reward=1000, difficulty=4, daa_mode=DaaMode.ASERT, target_time=120, half_life=600
        ),
        "55d8aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        "d0bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb01"
        "6402e80300520178040000000008ffffffffffffff1fbdc0c859797ea85d795d797ea87e5e7a"
        "7eaabc01147f77587f040000000088817600a26951797ca269c5527994537994030000019502"
        "580296020040a30200c0a47c08ffffffffffffff1fa37603000001967b959308ffffffffffff"
        "ff1fa376519f637551686b75757575577ae500a069567ae600a06901d053797e0cdec0e9aa76"
        "e378e4a269e69d7eaa76e47b9d547a818b76537a9c537ade789181547ae6939d636c755279cd"
        "01d853797e016a7e886778de519d7676009c63750100677660a163015093518067827c7e6868"
        "4c53d8aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        "aad0bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
        "016402e803005201787ec55480547c7e7e6c76009c63750100677660a163015093518067827c"
        "7e68687e5379ec78885379eac0e9885379cc519d75686d7551",
    ),
    "lwma_h0": (
        dict(height=0, max_height=100, reward=1000, difficulty=4, daa_mode=DaaMode.LWMA, target_time=60),
        "00d8aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        "d0bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb01"
        "6402e8030053013c040000000008ffffffffffffff1fbdc0c859797ea85d795d797ea87e5e7a"
        "7eaabc01147f77587f040000000088817600a26951797ca269c5527994537994030000019553"
        "7996020040a30200c0a47c08ffffffffffffff1fa37603000001967b959308ffffffffffffff"
        "1fa376519f637551686b75757575577ae500a069567ae600a06901d053797e0cdec0e9aa76e3"
        "78e4a269e69d7eaa76e47b9d547a818b76537a9c537ade789181547ae6939d636c755279cd01"
        "d853797e016a7e886778de519d7676009c63750100677660a163015093518067827c7e68684c"
        "53d8aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        "d0bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb01"
        "6402e8030053013c7ec55480547c7e7e6c76009c63750100677660a163015093518067827c7e"
        "68687e5379ec78885379eac0e9885379cc519d75686d7551",
    ),
    "lwma_h7": (
        dict(height=7, max_height=100, reward=1000, difficulty=8, daa_mode=DaaMode.LWMA, target_time=30),
        "57d8aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        "d0bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb01"
        "6402e8030053011e040000000008ffffffffffffff0fbdc0c859797ea85d795d797ea87e5e7a"
        "7eaabc01147f77587f040000000088817600a26951797ca269c5527994537994030000019553"
        "7996020040a30200c0a47c08ffffffffffffff1fa37603000001967b959308ffffffffffffff"
        "1fa376519f637551686b75757575577ae500a069567ae600a06901d053797e0cdec0e9aa76e3"
        "78e4a269e69d7eaa76e47b9d547a818b76537a9c537ade789181547ae6939d636c755279cd01"
        "d853797e016a7e886778de519d7676009c63750100677660a163015093518067827c7e68684c"
        "53d8aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        "d0bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb01"
        "6402e8030053011e7ec55480547c7e7e6c76009c63750100677660a163015093518067827c7e"
        "68687e5379ec78885379eac0e9885379cc519d75686d7551",
    ),
}


@pytest.mark.parametrize("label", list(_GOLDEN))
def test_contract_script_byte_matches_canonical_photonic(label):
    kwargs, golden_hex = _GOLDEN[label]
    params = DmintDeployParams(
        contract_ref=_CONTRACT_REF,
        token_ref=_TOKEN_REF,
        algo=DmintAlgo.SHA256D,
        **kwargs,
    )
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        got = build_dmint_contract_script(params).hex()
    assert got == golden_hex, f"{label}: pyrxd V2 covenant diverged from canonical Photonic"


def test_part_a_has_no_leading_op1_drop():
    # The redesign opens Part A straight at c0 c8 (OP_INPUTINDEX OP_OUTPOINTTXHASH);
    # the old shape prefixed 51 75 (OP_1 OP_DROP), which the redesign removed.
    from pyrxd.glyph.dmint.builders import _PART_A

    assert _PART_A[:2] == bytes.fromhex("c0c8")
    assert _PART_A[:2] != bytes.fromhex("5175")


def test_part_b4_preserves_newtarget():
    # 6b (TOALTSTACK) + 4× drop, not the old 5× drop that discarded newTarget.
    from pyrxd.glyph.dmint.types import _PART_B4

    assert _PART_B4.hex() == "6b75757575"
