#!/usr/bin/env python3
"""Generate conformance/bip44-derivation-vectors.json from an INDEPENDENT reference.

pyrxd is the *consumer* of this suite, not its producer. Every expected value
here is computed by `bip-utils` -- a separate implementation with no shared
lineage with pyrxd's `hd` module -- so the resulting vectors can catch a
self-consistent derivation bug that pyrxd's own goldens never could (they were
generated by the same code they test).

WHY THIS RUNS IN AN ISOLATED VENV
---------------------------------
`bip-utils` pins ``cbor2<6.0.0`` while pyrxd requires ``cbor2>=6.1``. The two
cannot coexist, so bip-utils is deliberately NOT a pyrxd dev dependency. This
generator is run out-of-band and its output is committed; the test that
consumes the committed JSON (tests/test_bip44_conformance_vectors.py) needs no
third-party package at all. Same shape as scripts/gen-photonic-vectors/.

USAGE
-----
    python3 -m venv /tmp/bip44-refvenv
    /tmp/bip44-refvenv/bin/pip install 'bip-utils>=2.12.1,<3.0.0'
    /tmp/bip44-refvenv/bin/python scripts/gen-bip44-derivation-vectors.py

REPRODUCIBILITY
---------------
All inputs derive from a fixed PRNG seed (``PRNG_SEED``), so re-running emits a
byte-identical file. The entropy values are PRNG-derived fixture material and
are NOT secrets -- never fund an address derived from them.

INDEPENDENCE CAVEAT (stated honestly, and repeated in the JSON provenance)
-------------------------------------------------------------------------
bip-utils and pyrxd both use `coincurve`/libsecp256k1 for elliptic-curve point
math, so a libsecp256k1 arithmetic bug would be invisible to this suite. What
IS independently covered is the failure class these vectors exist for: BIP39
seed derivation and normalization, BIP32 HMAC/CKD construction, hardened-index
math, coin_type path assembly, xprv/xpub serialization, and address/WIF
encoding.
"""

from __future__ import annotations

import json
import random
import sys
from pathlib import Path

# Fail loudly rather than silently producing pyrxd-derived "expected" values,
# which would make the whole suite circular and worthless.
if "pyrxd" in sys.modules:
    raise SystemExit("refusing to run: pyrxd is imported; expected values must come from the reference alone")

try:
    from bip_utils import (
        Bip32Slip10Secp256k1,
        Bip39SeedGenerator,
        P2PKHAddrEncoder,
        WifEncoder,
    )
except ImportError:  # pragma: no cover - generator-only path
    raise SystemExit(
        "bip-utils is required and must be installed in an ISOLATED venv "
        "(it pins cbor2<6, which conflicts with pyrxd). See this file's docstring."
    ) from None

import bip_utils

PRNG_SEED = 20260808
COIN_TYPES = (0, 236, 512)
# Mainnet Radiant shares Bitcoin's serialization constants (see pyrxd constants.py),
# so the reference's Bitcoin encoders are correct here.
P2PKH_NET_VER = b"\x00"
WIF_NET_VER = b"\x80"

OUT = Path(__file__).resolve().parent.parent / "conformance" / "bip44-derivation-vectors.json"


def _mnemonic_from_entropy(entropy: bytes) -> str:
    from bip_utils import Bip39EntropyBitLen, Bip39MnemonicGenerator  # noqa: F401

    return str(Bip39MnemonicGenerator().FromEntropy(entropy))


def _leaf(master, path: str):
    return master.DerivePath(path)


def _vector(idx: int, rng: random.Random) -> dict:
    entropy_bits = rng.choice((128, 256))
    entropy = bytes(rng.getrandbits(8) for _ in range(entropy_bits // 8))
    mnemonic = _mnemonic_from_entropy(entropy)
    # Exercise the passphrase path, including a non-ASCII case -- the exact input
    # class that exposed the missing NFKD normalization (fixed in #347).
    passphrase = rng.choice(("", "TREZOR", "correct horse", "café"))

    coin_type = COIN_TYPES[idx % len(COIN_TYPES)]
    account = rng.choice((0, 1, 2))
    change = rng.choice((0, 1))
    index = rng.choice((0, 1, 19, 20, 0x7FFFFFFF))

    seed = Bip39SeedGenerator(mnemonic).Generate(passphrase)
    master = Bip32Slip10Secp256k1.FromSeed(seed)
    account_path = f"44'/{coin_type}'/{account}'"
    leaf_path = f"{account_path}/{change}/{index}"
    acct = _leaf(master, account_path)
    leaf = _leaf(master, leaf_path)

    return {
        "id": f"sweep-{idx:04d}",
        "source": f"reference:bip-utils=={bip_utils.__version__}",
        "entropy_hex": entropy.hex(),
        "mnemonic": mnemonic,
        "passphrase": passphrase,
        "coin_type": coin_type,
        "account": account,
        "change": change,
        "index": index,
        "path": f"m/{leaf_path}",
        "expected": {
            "seed_hex": bytes(seed).hex(),
            "master_xprv": str(master.PrivateKey().ToExtended()),
            "master_xpub": str(master.PublicKey().ToExtended()),
            "account_xprv": str(acct.PrivateKey().ToExtended()),
            "account_xpub": str(acct.PublicKey().ToExtended()),
            "leaf_xprv": str(leaf.PrivateKey().ToExtended()),
            "leaf_xpub": str(leaf.PublicKey().ToExtended()),
            "address": P2PKHAddrEncoder.EncodeKey(leaf.PublicKey().KeyObject(), net_ver=P2PKH_NET_VER),
            "wif": WifEncoder.Encode(leaf.PrivateKey().KeyObject(), net_ver=WIF_NET_VER),
        },
    }


def main() -> None:
    rng = random.Random(PRNG_SEED)  # noqa: S311 - fixture material, not security-sensitive
    vectors = [_vector(i, rng) for i in range(60)]

    doc = {
        "schema": "radiant-bip44-derivation/1",
        "builder": (
            "pyrxd.hd: seed_from_mnemonic / Xprv.from_seed / ckd / "
            "Xprv.serialize / Xpub.__str__ / PublicKey.address / PrivateKey.wif"
        ),
        "provenance": (
            f"Expected values generated by bip-utils=={bip_utils.__version__}, an independent "
            "BIP32/39/44 implementation with no shared lineage with pyrxd's hd module, via "
            "scripts/gen-bip44-derivation-vectors.py. pyrxd is the CONSUMER of this suite, not "
            "the reference producer -- the inverse of the dMint V2 suite. CAVEAT: bip-utils and "
            "pyrxd share coincurve/libsecp256k1 for EC point math, so a libsecp256k1 arithmetic "
            "bug would be invisible here; BIP39 seed derivation/normalization, BIP32 HMAC/CKD, "
            "hardened-index math, coin_type path assembly, and xprv/xpub/address/WIF "
            "serialization ARE independently covered."
        ),
        "notes": (
            "Radiant shares Bitcoin's xprv/xpub version bytes, P2PKH prefix (0x00) and WIF "
            "prefix (0x80), so a Bitcoin reference is byte-correct for Radiant mainnet; only "
            "the BIP44 coin_type differs. Coin types 0 (Photonic <=v2 / Electron-Radiant), 236 "
            "(pre-#14 pyrxd) and 512 (SLIP-0044, pyrxd default) are all live recovery paths -- "
            "see src/pyrxd/hd/discovery.py. Entropy values are PRNG fixture material, not "
            "secrets: never fund an address derived from them."
        ),
        "meta": {
            "generator_prng_seed": PRNG_SEED,
            "reference_impl": f"bip-utils=={bip_utils.__version__}",
            "vector_count": len(vectors),
        },
        "radiant_bip44_sweep": vectors,
    }

    OUT.write_text(json.dumps(doc, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(vectors)} vectors)")


if __name__ == "__main__":
    main()
